### PR TITLE
Cmakelists: Redo the lists

### PR DESCRIPTION
**Pull request by 1480c1**
Similar to https://github.com/OpenVisualCloud/SVT-AV1/pull/276,
Closes #200 since it's changes are included
Closes #215 since it's changes are included
Has most of the changes from #135 with the exception of mxsave

### CODE REVIEW

**Comment by 1480c1** [comment]
It seems that it only errors `make[2]: *** No rule to make target 'Source/Lib/ASM_SSSE3/CMakeFiles/ASM_SSSE3.dir/EbAvcStyleMcp_Intrinsic_SSSE3.c.o', needed by '../Bin/Release/libSvtHevcEnc.so.1'.  Stop.` when doing make in non-parallel.

**Comment by 1480c1** [comment]
Okay, fixed

**Comment by tianjunwork** [comment]
@1480c1 Thanks a lot! 
Does it build on APPLE and runs OK? If so, could you also update the README?
Any other changes that user should know?

**Comment by 1480c1** [comment]
There are still the problems of the `#error OS not supported` etc, but I will rebase #135 and modify that based on these changes.
I will update README once I can confirm that to work

**Comment by 1480c1** [comment]
Although, I am concerned about d99ca9a since I'm not very well versed on programming in C
I only did it because with these changes, rather than compiling C_DEFAULT, ASM_SSE4_1, etc, it will combine all of the object files from those folders (with their cflags properly set) into libSvtHevcEnc.so etc, and the compiler was warning about duplicates

**Comment by 1480c1** [comment]
@tianjunwork, can you confirm if the encoder works properly on the master branch with linux? as in encode and confirm video is proper?

On `Linux 4.18.0-20-generic #21~18.04.1-Ubuntu SMP, Intel(R) Core(TM) i5-7200U` on master branch, the video is bad:
image
I'm hoping it's just that something is wrong with my computer

**Comment by tianjunwork** [comment]
@1480c1 what's the command you used on Ubuntu? and video input format: resolution, bit-depth, color format? You saw bad video on master only, without this PR, right?

**Comment by 1480c1** [comment]
I used the akiyo_cif.y4m from xiph
`./SvtHevcEncApp -i ./akiyo_cif.y4m -w 352 -h 288  -fps-num 30000 -fps-denom 1001 -b test.h265`

**Comment by 1480c1** [comment]
Yes I saw it on master while trying to test reproducibility with this pr

**Comment by tianjunwork** [comment]
@1480c1 the video corruption is reproduced on master. Thanks for reporting.

**Comment by tianjunwork** [comment]
Hi @1480c1,  *.y4m is a file container not pure yuv data, not supported by SVT app.
https://wiki.multimedia.cx/index.php?title=YUV4MPEG2

**Comment by 1480c1** [comment]
I see, I will test with yuv when I canWill it be possible to port y4m support from svt-av1?
-------- Original message --------From: Jun <notifications@github.com> Date: 6/4/19  10:06 PM  (GMT-08:00) To: OpenVisualCloud/SVT-HEVC <SVT-HEVC@noreply.github.com> Cc: Christopher Degawa <cddegawa@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [OpenVisualCloud/SVT-HEVC] Cmakelists: Redo the lists (#206) Hi @1480c1,  *.y4m is a file container not pure yuv data, not supported by SVT app.
https://wiki.multimedia.cx/index.php?title=YUV4MPEG2

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/OpenVisualCloud/SVT-HEVC/pull/206?email_source=notifications\u0026email_token=AB7VPRTH5HTI2NFVE3RUXVDPY5CVPA5CNFSM4HSOSEOKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODW6TR2I#issuecomment-498940137",
"url": "https://github.com/OpenVisualCloud/SVT-HEVC/pull/206?email_source=notifications\u0026email_token=AB7VPRTH5HTI2NFVE3RUXVDPY5CVPA5CNFSM4HSOSEOKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODW6TR2I#issuecomment-498940137",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by EwoutH** [comment]
@tianjunwork SVT-AV1 supports y4m input: https://github.com/OpenVisualCloud/SVT-AV1/blob/master/Source/App/EncApp/EbAppInputy4m.c

**Comment by tianjunwork** [comment]
> @tianjunwork SVT-AV1 supports y4m input: https://github.com/OpenVisualCloud/SVT-AV1/blob/master/Source/App/EncApp/EbAppInputy4m.c

**Comment by tianjunwork** [comment]
@EwoutH Thanks pointing out the implementation:)

**Comment by tianjunwork** [comment]
Hi @1480c1 I got link error on Ubuntu. Windows build is fine.
[100%] Linking C executable ../../../../../Bin/Release/SvtHevcEncApp
../../../../../Bin/Release/libSvtHevcEnc.so.1: undefined reference to `UpdateNeighborDcIntraPred_AVX2_INTRIN'
../../../../../Bin/Release/libSvtHevcEnc.so.1: undefined reference to `Luma4SampleEdgeDLFCore16bit_SSSE3_INTRIN'
../../../../../Bin/Release/libSvtHevcEnc.so.1: undefined reference to `PictureAdditionKernel32x32_SSE2_INTRIN'

**Comment by 1480c1** [comment]
I will look into it when I can, right now, I'm in Alaska with almost no connection

**Comment by 1480c1** [comment]
@tianjunwork, can you post the commands? I cannot easily reproduce

I will check compile order still

**Comment by tianjunwork** [comment]
@1480c1 
cd Build/linux
./build.sh

**Comment by 1480c1** [comment]
even using the build.sh, I am unable to get the undefined references error, although the hint is probably that the object files are no longer compiled separately

**Comment by tianjunwork** [comment]
Afer "-- Configuring done"
I got lots of cmake errors:
CMake Error at Source/Lib/Codec/CMakeLists.txt:204 (target_link_libraries):
  Error evaluating generator expression:

    $<TARGET_OBJECTS:C_DEFAULT>

  The evaluation of the TARGET_OBJECTS generator expression is only suitable
  for consumption by CMake.  It is not suitable for writing out elsewhere.

**Comment by 1480c1** [comment]
What CMake version are you using?

**Comment by 1480c1** [comment]
How about now?

File: Source/Lib/pkg-config.pc.in [hunk 1]
```diff
@@ -1,9 +1,9 @@
 prefix=@CMAKE_INSTALL_PREFIX@
```
Comment (tianjunwork) [inline Source/Lib/pkg-config.pc.in]: remove unused "prefix"?

**Comment by tianjunwork** [comment]
> What CMake version are you using?

cmake version 3.5.1

**Comment by tianjunwork** [comment]
@1480c1 Build pass with the new commit.

File: Source/Lib/pkg-config.pc.in (hunk 1 above)
Comment (1480c1) [reply Source/Lib/pkg-config.pc.in]: I would probably prefer to leave it for formality sake since most other pc files I've seen had prefix set, although they usually had `${prefix}` for the other parts so I might do that instead

**Comment by 1480c1** [comment]
> @1480c1 Build pass with the new commit.

Nice

File: Source/Lib/pkg-config.pc.in (hunk 1 above)
Comment (tianjunwork) [reply Source/Lib/pkg-config.pc.in]: Sure. Thx.

Comment (1480c1) [reply Source/Lib/pkg-config.pc.in]: changed to use `${prefix}` for the rest of the dirs

**Comment by 1480c1** [comment]
Any other changes that would be preferred?

**Comment by intelmark** [comment]
Took a look at these cmake changes.

1)	On Windows an unnecessary “release” folder is getting created for both debug and release.  Suitable Windows bin files are created in the /bin/release/debug and /bin/release/release folders.

./build.bat 2017 clean
./build.bat 2017 debug -> /bin/release/debug – not sure why getting a release folder

./build.bat 2017 clean
./build.bat 2017 release-> /bin/release/release – not sure why getting a release folder

2)	Also seeing some Failed messages coming from cmake when building on both Linux and windows.  It’s unclear if these are new or meaningful.  Jun mentioned she hasn't seen them before, but thought I'd ask if you have any thoughts. (ignore line numbers:)

1)	-- Performing Test C_FLAG_Wextra
2)	-- Performing Test C_FLAG_Wextra - Failed
3)	-- Performing Test C_FLAG_Wformat
4)	-- Performing Test C_FLAG_Wformat - Failed
5)	-- Performing Test C_FLAG_Wformat_security
6)	-- Performing Test C_FLAG_Wformat_security - Failed
7)	-- Performing Test C_FLAG_mavx
8)	-- Performing Test C_FLAG_mavx - Failed
9)	-- Performing Test C_FLAG_fstack_protector_strong
10)	-- Performing Test C_FLAG_fstack_protector_strong - Failed
11)	-- Performing Test C_FLAG_fvisibility_hidden
12)	-- Performing Test C_FLAG_fvisibility_hidden - Failed
13)	-- Performing Test C_FLAG_fPIE
14)	-- Performing Test C_FLAG_fPIE - Failed
15)	-- Performing Test C_FLAG_fPIC
16)	-- Performing Test C_FLAG_fPIC - Failed
17)	-- Performing Test C_FLAG_D_FORTIFY_SOURCE_2
18)	-- Performing Test C_FLAG_D_FORTIFY_SOURCE_2 - Success
19)	-- Performing Test C_FLAG_GS
20)	-- Performing Test C_FLAG_GS - Success
21)	-- Performing Test C_FLAG_sdl
22)	-- Performing Test C_FLAG_sdl - Success
23)	-- Performing Test C_FLAG_MP
24)	-- Performing Test C_FLAG_MP - Success
25)	-- Performing Test C_FLAG_O2
26)	-- Performing Test C_FLAG_O2 - Failed
27)	-- Performing Test C_FLAG_O3
28)	-- Performing Test C_FLAG_O3 - Failed
29)	-- Performing Test C_FLAG_g
30)	-- Performing Test C_FLAG_g - Failed
31)	-- Performing Test C_FLAG_O0
32)	-- Performing Test C_FLAG_O0 - Failed
33)	-- Performing Test C_FLAG_Og
34)	-- Performing Test C_FLAG_Og - Failed
35)	-- Performing Test C_FLAG_msse2
36)	-- Performing Test C_FLAG_msse2 - Failed
37)	-- Performing Test C_FLAG_static_intel
38)	-- Performing Test C_FLAG_static_intel - Failed
39)	-- Performing Test C_FLAG_mssse3
40)	-- Performing Test C_FLAG_mssse3 - Failed
41)	-- Performing Test C_FLAG_msse4_1
42)	-- Performing Test C_FLAG_msse4_1 - Failed
43)	-- Performing Test C_FLAG_mavx2
44)	-- Performing Test C_FLAG_mavx2 - Failed
45)	-- Performing Test C_FLAG_Qwd10148
46)	-- Performing Test C_FLAG_Qwd10148 - Failed
47)	-- Performing Test C_FLAG_Qwd10010
48)	-- Performing Test C_FLAG_Qwd10010 - Failed
49)	-- Performing Test C_FLAG_Qwd10157
50)	-- Performing Test C_FLAG_Qwd10157 - Failed
51)	-- Configuring done

**Comment by 1480c1** [comment]
The cflags come from testing if your c compiler supports those flags ( for a compiler agnostic way of setting the flags) so it would fails if using `cl.exe` with `-mavx` but work with `/MP`


For the folder thing, I will try to look into it tonight

**Comment by 1480c1** [comment]
Essentially, you can ignore the failed/success cflags unless you are using a compiler you are sure that uses them

**Comment by 1480c1** [comment]
I have a feeling that since we are using `set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${PROJECT_SOURCE_DIR}/Bin/${CMAKE_BUILD_TYPE` and for the `build.bat` we are using `-DCMAKE_CONFIGURATION_TYPES="Debug;Release"` leading to converting the ; into a slash.

This is essentially a defect in using build type in the path and using a multiconfig generator such as vs

**Comment by 1480c1** [comment]
I will submit a pr for the build. Bat to remedy it

**Comment by 1480c1** [comment]
Any more questions or concerns?

File: CMakeLists.txt [hunk 2]
```diff
@@ -38,56 +38,129 @@ set(SVT_HEVC_SOVERSION 1)
...
-    if (MSVC)
-        set(CMAKE_C_FLAGS " /GS /sdl ")
-        set(CMAKE_CXX_FLAGS " /GS /sdl ")
-        set(CMAKE_EXE_LINKER_FLAGS " /NXCompat /DynamicBase ")
-        set(CMAKE_SHARED_LINKER_FLAGS " /NXCompat /DynamicBase ")
+set(flags_to_test
+    -Wextra
+    -Wformat
+    -Wformat-security
+    -mavx
```
Comment (tianjunwork) [inline CMakeLists.txt]: should it be avx2 here? why don't use native anymore?

File: Source/Lib/ASM_SSE4_1/EbTransforms_Intrinsic_SSE4_1.c [hunk 3]
```diff
@@ -7,6 +7,213 @@
 #include <smmintrin.h>
 #include "EbTransforms_SSE4_1.h"
 
+EB_ALIGN(16) const EB_S16 TransformAsmConst_SSE4_1[] = {
```
Comment (tianjunwork) [inline Source/Lib/ASM_SSE4_1/EbTransforms_Intrinsic_SSE4_1.c]: why the change here?

File: CMakeLists.txt (hunk 2 above)
Comment (1480c1) [reply CMakeLists.txt]: I think it's been mavx, although I would prefer to not use mavx in top level since
`GCC depresses SSEx instructions when -mavx is used. Instead, it generates new AVX instructions or AVX equivalence for all SSEx instructions when needed.` from [here](https://gcc.gnu.org/onlinedocs/gcc/x86-Options.html) and imo it's better to not use native unless the end user sets that as cflags because if they wish to compile once and copy to other servers, it might not work due to native flag

File: Source/Lib/ASM_SSE4_1/EbTransforms_Intrinsic_SSE4_1.c (hunk 3 above)
Comment (1480c1) [reply Source/Lib/ASM_SSE4_1/EbTransforms_Intrinsic_SSE4_1.c]: I kept getting error for undefined with it, I'm going to try again with the commit reverted with the others fixed

File: CMakeLists.txt (hunk 2 above)
Comment (1480c1) [reply CMakeLists.txt]: Actually, thats a copy over from svt-av1, need to delete

File: Source/Lib/ASM_SSE4_1/EbTransforms_Intrinsic_SSE4_1.c (hunk 3 above)
Comment (1480c1) [reply Source/Lib/ASM_SSE4_1/EbTransforms_Intrinsic_SSE4_1.c]: It seems I might be able to revert

**Comment by 1480c1** [comment]
I found out that the sse2 and ssse3 folders require sse4.1, will fix once I'm on a computer

File: CMakeLists.txt (hunk 2 above)
Comment (1480c1) [reply CMakeLists.txt]: I've added an option to add back the march=native flag

**Comment by tianjunwork** [comment]
@intelmark Could help to verify on Windows and Ubuntu once again. Thx. If no issue, will merge it soon.

**Comment by intelmark** [comment]
Still seeing this issue:
On Windows an unnecessary “release” folder is getting created for both debug and release. Suitable Windows bin files are created in the /bin/release/debug and /bin/release/release folders.
./build.bat 2017 clean
./build.bat 2017 debug -> /bin/release/debug – not sure why getting a release folder

./build.bat 2017 clean
./build.bat 2017 release-> /bin/release/release – not sure why getting a release folder

Linux builds work fine.

**Comment by 1480c1** [comment]
Try `cmake ../../.. -DCMAKE_BUILD_TYPE=Release`

**Comment by 1480c1** [comment]
and `cmake --build .`

**Comment by 1480c1** [comment]
It should not generate another folder again, if that is true, I will submit a pr for the batch file

**Comment by 1480c1** [comment]
@intelmark you can try https://patch-diff.githubusercontent.com/raw/OpenVisualCloud/SVT-HEVC/pull/216.patch with the build.bat to see if that solved your problem

**Comment by intelmark** [comment]
Something to note:
On Windows in CMakeLists.txt in SVT-HEVC root:

Changing
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${PROJECT_SOURCE_DIR}/Bin/${CMAKE_BUILD_TYPE}/)
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${PROJECT_SOURCE_DIR}/Bin/${CMAKE_BUILD_TYPE}/)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${PROJECT_SOURCE_DIR}/Bin/${CMAKE_BUILD_TYPE}/)

to:
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${PROJECT_SOURCE_DIR}/Bin/)
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${PROJECT_SOURCE_DIR}/Bin/)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${PROJECT_SOURCE_DIR}/Bin/)

will eliminate the extra "Bin/Release" folder from getting created.  Appropriate binary files are being built in the appropriate folders.

**Comment by 1480c1** [comment]
Yea, I do wish to remove reliance on build type for folders, but doing so will deviate from av1 and vp9. Although one benefit is that ATM, there are no Auto tests in Travis yet.


@tianjunwork would that change be fine for svt-hevc?  Only conflict I see would be if you build release then debug or visa versa, the binaries will override each other (usually circumvented by outputting bins to the binary dir[ the build folder])

File: Source/Lib/pkg-config.pc.in [hunk 4]
```diff
@@ -1,9 +1,9 @@
...
-includedir=${prefix}/@CMAKE_INSTALL_INCLUDEDIR@
+includedir=${prefix}/@CMAKE_INSTALL_INCLUDEDIR@/svt-hevc
 libdir=${prefix}/@CMAKE_INSTALL_LIBDIR@
 
 Name: SvtHevcEnc
 Description: SVT (Scalable Video Technology) for HEVC encoder library
 Version: 1.3.0
-Libs: -L${libdir} -lSvtHevcEnc -lpthread
+Libs: -L${libdir} -lSvtHevcEnc @LIBS_PRIVATE@
```
Comment (wiiaboo) [inline Source/Lib/pkg-config.pc.in]: If they're private libs only required for static linking the convention is to use `Libs.private`. This is supported by both pkg-config and pkgconf.

Comment (1480c1) [reply Source/Lib/pkg-config.pc.in]: Yea, I think I tried that before, but something failed. I can try again

**Comment by tianjunwork** [comment]
Hi @1480c1, Let's don't deviate from AV1 and VP9 in case of confusing others.

File: Source/Lib/pkg-config.pc.in (hunk 4 above)
Comment (1480c1) [reply Source/Lib/pkg-config.pc.in]: The ffmpeg build failed due to pthread stuff

**Comment by 1480c1** [comment]
@tianjunwork sure

File: Source/Lib/pkg-config.pc.in (hunk 4 above)
Comment (tianjunwork) [reply Source/Lib/pkg-config.pc.in]: GStreamer plugin build pass with this PR.

Comment (1480c1) [reply Source/Lib/pkg-config.pc.in]: I noticed that the lib is not linked to pthread but the app is, is that ok?

Comment (tianjunwork) [reply Source/Lib/pkg-config.pc.in]: Isn't it always the executable which links all the dependencies? svt lib should not link to other libs.

Comment (1480c1) [reply Source/Lib/pkg-config.pc.in]: I see pthread stuff in some files in the codec folder

Comment (1480c1) [reply Source/Lib/pkg-config.pc.in]: I guess you are probably right

Comment (1480c1) [reply Source/Lib/pkg-config.pc.in]: I guess you are probably right

Comment (wiiaboo) [reply Source/Lib/pkg-config.pc.in]: Yeah, compiling this lib (the object code) only requires the headers, both for static or shared compilation; but static executables will need all the dependencies from this lib when linking.
So if svt requires Threads for static compilation, they should be specified on the pkg-config file, in a `Libs.private:` line.
When compiling the static executables that depend on svt, you then use `--static` flag, i.e. `pkg-config --static --libs`, to get both the libs in `Libs:` and the ones in `Libs.private:`.

Comment (1480c1) [reply Source/Lib/pkg-config.pc.in]: Although if I do link the lib to pthread and change the PKG config to libs. Private, ffmpeg compiled fine

**Comment by tianjunwork** [comment]
Hi @1480c1 I may wait for OpenVisualCloud/SVT-AV1#276 to get reviewed also to keep sync with AV1.

**Comment by 1480c1** [comment]
Sure sure

**Comment by tianjunwork** [comment]
Hi @1480c1, is this PR still sync with OpenVisualCloud/SVT-AV1#276?

**Comment by 1480c1** [comment]
Should be, will check again over im in my laptop

**Comment by 1480c1** [comment]
Seems to be matching ( for the parts that align )

**Comment by tianjunwork** [comment]
Hi @lijing0010 @Austin-Hu , could review also? If no comment, I will merge it soon.
